"""Word and email export. The daily debrief .docx is the actual client deliverable."""

from __future__ import annotations

import re
from pathlib import Path

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Pt, RGBColor

from .config import EXPORT_DIR
from .schema import Debrief, InsightCard

ACCENT = RGBColor(0x00, 0x30, 0x87)
MUTED = RGBColor(0x5A, 0x5A, 0x5A)


def _strip_ids(text: str) -> str:
    return re.sub(r"\s*\[[0-9a-f]{6,12}\]", "", text)


def _heading(doc: Document, text: str, size: int = 13) -> None:
    para = doc.add_paragraph()
    para.paragraph_format.space_before = Pt(12)
    para.paragraph_format.space_after = Pt(4)
    run = para.add_run(text.upper())
    run.bold = True
    run.font.size = Pt(size)
    run.font.color.rgb = ACCENT


def build_docx(
    debrief: Debrief,
    cards: list[InsightCard] | None = None,
    include_citations: bool = True,
    include_appendix: bool = True,
) -> Path:
    cards = cards or []
    by_id = {c.id: c for c in cards}
    doc = Document()

    normal = doc.styles["Normal"]
    normal.font.name = "Calibri"
    normal.font.size = Pt(10.5)

    title = doc.add_paragraph()
    run = title.add_run(f"{debrief.conference} — Daily Conference Debrief")
    run.bold = True
    run.font.size = Pt(18)
    run.font.color.rgb = ACCENT

    sub = doc.add_paragraph()
    sub_run = sub.add_run(
        f"Prepared for {debrief.client}  |  {debrief.day:%A, %d %B %Y}  |  "
        f"Generated {debrief.generated_at:%H:%M}"
    )
    sub_run.font.size = Pt(9)
    sub_run.font.color.rgb = MUTED

    if debrief.headline:
        head = doc.add_paragraph()
        head_run = head.add_run(_strip_ids(debrief.headline))
        head_run.bold = True
        head_run.font.size = Pt(11.5)

    _heading(doc, "Executive summary")
    doc.add_paragraph(_strip_ids(debrief.executive_summary))

    for section in debrief.sections:
        _heading(doc, section.heading)
        if section.body:
            doc.add_paragraph(_strip_ids(section.body))
        for bullet in section.bullets:
            doc.add_paragraph(_strip_ids(bullet), style="List Bullet")
        if include_citations and section.citations:
            cite = doc.add_paragraph()
            cite_run = cite.add_run("Sources: " + "; ".join(dict.fromkeys(section.citations)))
            cite_run.font.size = Pt(8)
            cite_run.italic = True
            cite_run.font.color.rgb = MUTED

    if debrief.question_answers:
        _heading(doc, "Responses to your standing questions")
        for item in debrief.question_answers:
            qp = doc.add_paragraph()
            q_run = qp.add_run(item["question"])
            q_run.bold = True
            doc.add_paragraph(_strip_ids(item["answer"]))
            if include_citations and item.get("citations"):
                cite = doc.add_paragraph()
                cite_run = cite.add_run("Sources: " + "; ".join(dict.fromkeys(item["citations"])))
                cite_run.font.size = Pt(8)
                cite_run.italic = True
                cite_run.font.color.rgb = MUTED

    if debrief.watchlist:
        _heading(doc, "Watchlist for tomorrow")
        for item in debrief.watchlist:
            doc.add_paragraph(_strip_ids(item), style="List Bullet")

    if include_appendix and debrief.card_ids:
        doc.add_page_break()
        _heading(doc, "Appendix — source evidence", size=14)
        for card_id in debrief.card_ids:
            card = by_id.get(card_id)
            if not card:
                continue
            para = doc.add_paragraph()
            run = para.add_run(card.title or "(untitled)")
            run.bold = True
            meta = " | ".join(
                x for x in [card.company, card.asset, card.indication, card.phase] if x
            )
            if meta:
                m = doc.add_paragraph().add_run(meta)
                m.font.size = Pt(8.5)
                m.font.color.rgb = MUTED
            for dp in card.data_points:
                doc.add_paragraph(dp, style="List Bullet")
            if card.evidence.thumbnail_path and Path(card.evidence.thumbnail_path).exists():
                try:
                    from docx.shared import Inches

                    doc.add_picture(card.evidence.thumbnail_path, width=Inches(2.6))
                except Exception:  # noqa: BLE001
                    pass
            src = doc.add_paragraph().add_run(f"Source: {card.citation()}")
            src.font.size = Pt(8)
            src.italic = True
            src.font.color.rgb = MUTED

    footer = doc.add_paragraph()
    footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
    f_run = footer.add_run(
        "Generated by the Conference Intelligence Assistant. AI-assisted draft — "
        "review before client circulation."
    )
    f_run.font.size = Pt(7.5)
    f_run.font.color.rgb = MUTED

    safe_client = re.sub(r"[^A-Za-z0-9_-]+", "_", debrief.client or "client")
    safe_conf = re.sub(r"[^A-Za-z0-9_-]+", "_", debrief.conference or "conference")
    out = EXPORT_DIR / f"{safe_conf}_{debrief.day:%Y%m%d}_{safe_client}_debrief.docx"
    doc.save(out)
    return out


def build_email(debrief: Debrief) -> str:
    lines = [
        f"Subject: {debrief.conference} — Day debrief, {debrief.day:%d %b %Y}",
        "",
        f"Hi {debrief.client} team,",
        "",
        "Today's debrief from the floor:",
        "",
        _strip_ids(debrief.executive_summary),
        "",
    ]
    for section in debrief.sections[:4]:
        lines.append(section.heading.upper())
        for bullet in section.bullets[:5]:
            lines.append(f"  • {_strip_ids(bullet)}")
        lines.append("")
    if debrief.question_answers:
        lines.append("YOUR STANDING QUESTIONS")
        for item in debrief.question_answers:
            lines.append(f"  Q: {item['question']}")
            lines.append(f"  A: {_strip_ids(item['answer'])}")
            lines.append("")
    lines += ["Full debrief attached.", "", "Best regards,", "Conference Intelligence Team"]
    return "\n".join(lines)
